### ISSUE TITLE
Non deterministic IAAO statistics

### ISSUE THREAD

**Issue by nmarchio** [erhla/cmfproperty#6]
Hey @erhla -- 

In the process of replicating the COD, PRD, and PRB statistics generated via the make_report function I noticed that all three  IAAO stats were slightly different from what you'd get if you were to manually compute them. I believe bootstrapping is a good solution for estimating errors but unsure if that is the best choice for estimating the actual IAAO performance indices. Or alternatively perhaps what you can do is provide an option in the make_reports fucntion to generate the statistics without bootstrapping. 

As a comparison this is what I got manually computing them without bootstrapping vs using make_report:
* COD 40.4 (manual) vs 34.55 (make_report)
* PRD 1.12 (manual) vs 0.843, 1.058, 1.312, 1.177, 1.027 (make_report .. this was least stable)
* PRB -0.1071028 (manual) vs -0.088 (make_report) 

Below is the function I used modeled directly after your code w/o bootstrapping (referencing this: https://github.com/cmf-uchicago/cmfproperty/blob/master/R/iaao_stats.R#L1-L33)

```
#' @param data dataframe of data
#' @param assessment_value_col string of assessment_value_col name
#' @param sale_price_col string of sale_price_col name
#' @return dataframe 
gen_iaao_stats <- function(data, assessment_value_col, sale_price_col) { 
  df_iaao <- data %>% 
    rename_at(vars(c(assessment_value_col, sale_price_col)), function(x) c('assessment_value','sale_price')) %>% 
    mutate(av_ratio = assessment_value/sale_price,
           log2 = log(2),
           count = 1) %>%
    mutate(cod = 100 * sum(abs(av_ratio - stats::median(av_ratio)))/(n() * stats::median(av_ratio)),
           prd = mean(av_ratio, na.rm = TRUE)/stats::weighted.mean(av_ratio, sale_price, na.rm = TRUE),
           prb_value = 0.50 * (assessment_value/median(av_ratio)) + 0.50 * sale_price,
           prb_ln_value = log(prb_value)/log(2),
           prb_pct_diff = (av_ratio - median(av_ratio))/median(av_ratio)
    )
  prb_model <- linear_reg() %>% 
    fit(prb_pct_diff ~ prb_ln_value,  data = df_iaao) %>%
    tidy(., conf.int = TRUE) 
  iaao_out <- list('cod' = c(unique(df_iaao$cod)) ,
                   'prd' = c(unique(df_iaao$prd)) ,
                   'prb' = c(prb_model %>% filter(term == 'prb_ln_value') %>% select(estimate) %>% distinct() %>% pull())) %>%
    as.data.frame()
  return(iaao_out)
}
```

```
test <- gen_iaao_stats(data = data_input, assessment_value_col = 'ASSESSEDVALUE', sale_price_col = 'sale_price')
  ```

**Comment by erhla** [comment]
Thanks @nmarchio. I think that this is an interesting idea. Generally, I was thinking about a tradeoff between presenting the most accurate numbers and a 'false' sense of precision when results are more marginal so I only have bootstrapping presently. In most cases, the difference is negligible but with small samples or more marginal cases you will see highly variable results which may lead to presenting the results in a way that shows this lack of precision such as a range. Since we are viewing sales as an imperfect/noisy measure for true market value, any reasonable approach which states assumptions is valid so I'll work to incorporate this.

**Comment by nmarchio** [comment]
Cool, that sounds good. Thanks, @erhla -- I think being able to turnoff bootstrapping is especially useful in situations where an assessor's office may want to check the numbers (or challenge them) or replicate them, and having stable results would be important. Also note: these results were based on the recent Detroit sample which had an n-size of 2,000 for one year.
